spring:
  application:
    name: config-service-server
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  data:
    mongodb:
      uri: ${MONGO_URL}
server:
  port: 8080